### ISSUE TITLE
Spacing bug

### ISSUE THREAD

**Issue by SolidRhino** [ironicbadger/ansible-role-docker-compose-generator#41]
If I create the following directory structure:

```bash
services
└── solid-dog
    ├── 01-Caddy
    │   └── compose.yaml
    └── 99-ExtraConfig
        └── compose.yaml
```

And the compose file in the ExtraConfig directory contains:

```yaml
services:
  
networks:
  proxy:
  caddy-macvlan:
    name: caddy-macvlan
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "192.168.50.0/24"
          gateway: "192.168.50.1"

volumes:
  caddy_data:
  caddy_config:
```

The compose file that is generated is not correct:

```yaml
...
volumes:
      - caddy_data:/data
      - cddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      caddy-macvlan:
        ipv4_address: 192.168.50.5
      proxy:
  networks:
  proxy:
  caddy-macvlan:
    name: caddy-macvlan
    driver: macvlan
...
```

You can see that the spacing of the `networks:` line is incorrect.

**Comment by futuros** [comment]
Pretty sure this is caused by these lines
```
{{ lookup('template', file.src)
         | regex_replace('^(---|services:)\s*\n*', '')
         | regex_replace('^', '  ') }}
```

The second regex gives each line an additional 2 spaces indentation.
But because lookup('template') handles the whole file as a single line this only applies to the first occurence

The role expects yaml files already to be indented correctly and assumes a service: tag in place. 
So this code makes more sense

```
{{ lookup('template', file.src)
         | regex_replace('^(---)\s*\n*', '')
         | regex_replace('^(services:)\s*\n*', '')

```

I also fixed the ---|services in two lines.
Because in cause of a --- starting line it would never remove the services: part. Because it is not at the start of the line.

**Comment by ironicbadger** [comment]
Does #45 resolve this for you?

**Comment by futuros** [comment]
If you have these valid compose files (abbreviated for the example)
```
---
services:
  traefik:
    container_name: traefik
    image: traefik:v2.10    
``` 

```
---
services:
  authelia:
    container_name: authelia
    image: authelia/authelia:latest
```
And extra compose stuff
```
---
services:

networks:
  proxy:
  caddy-macvlan:
    name: caddy-macvlan
```

You would get a compose file that still contains multiple services tags
```
# Generated by ironicbadger.docker-compose-generator
# badger badger badger mushroom mushrooooom..
  services:
    traefik:
      container_name: traefik
      image: traefik:v2.10
  services:
    authelia:
      container_name: authelia
      image: authelia/authelia:latest
  services:
  
  networks:
    proxy:
    caddy-macvlan:
      name: caddy-macvlan
```

I know i can remove all the '---' lines from my compose file, but a valid yaml does contain that line. And it looks like you intent to filter it away with the regex.
Adding the (?m) flag to this regex would solve that ` | regex_replace('(?m)^(---|services:)\s*\n*', '')` 

The files also contains additional indentation for all lines. I don't see why you need that if you already provide correct compose files to begin with. 
But that might also be the answer ofcourse :). That it is to support yaml files without any indenting at all like
```
traefik:
  container_name: traefik
  image: traefik:v2.10
```
Maybe that something to make configurable?
